language: python
python:
  - "3.6"
  
#cache:
#- pip
# command to install dependencies
install:
  pip install -r requirements.txt --prefer-binary
  #- python setup.py install
  
 # command to run tests
script:
  - pytest
